"""empty message

Revision ID: 276c637cf803
Revises: 5cbf698d6d6a
Create Date: 2025-06-05 14:36:01.005074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '276c637cf803'
down_revision = '5cbf698d6d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites_character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_from_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_from_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites_planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planet_from_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planet_from_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites_vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_from_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vehicle_from_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorites_planets')
    op.drop_table('favorites_characters')
    op.drop_table('favorites_vehicles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites_vehicles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vehicle_from_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorites_vehicles_user_id_fkey'),
    sa.ForeignKeyConstraint(['vehicle_from_id'], ['vehicles.id'], name='favorites_vehicles_vehicle_from_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorites_vehicles_pkey')
    )
    op.create_table('favorites_characters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('character_from_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_from_id'], ['characters.id'], name='favorites_characters_character_from_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorites_characters_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorites_characters_pkey')
    )
    op.create_table('favorites_planets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('planet_from_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['planet_from_id'], ['planets.id'], name='favorites_planets_planet_from_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorites_planets_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorites_planets_pkey')
    )
    op.drop_table('favorites_vehicle')
    op.drop_table('favorites_planet')
    op.drop_table('favorites_character')
    # ### end Alembic commands ###
